on:
  push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Trigger external workflow and watch
        run: |
          ./gh_dispatch.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}