name: Dockerfile Standard Checks
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:  
  build:
    runs-on: ubuntu-latest
    environment: production-registry
    steps:
      - uses: deriv-iac/shared-actions/build_and_test@main
        with:
          images: jothimanideriv/ghaction-poc
          project_type: skip
          dockerfile: "./Dockerfile"
          push: false
