name: Dockerfile Standard Checks
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:  
  build_and_test:
    runs-on: ubuntu-latest
    environment: production-deploy-k3s
    steps:
      - uses: deriv-iac/shared-actions/deploy_to_k3s@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

