on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Linter for Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy step
        run: 
          | 
          echo "Deployment steps go here"
          echo "$GH_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.TEST_SECRET }}