name: Dockerfile Standard Checks
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:  
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: deriv-iac/shared-actions/build_and_test@master
        with:
          images: jothimanideriv/ghaction-poc
          project_type: skip
          dockerfile: "./Dockerfile"
          push: false
  push_to_prod_registry:
    runs-on: ubuntu-latest
    environment: production-registry
    needs: build_and_test
    steps:
      - uses: deriv-iac/shared-actions/push_to_registry@master
        with:
          images: jothimanideriv/ghaction-poc
          project_type: skip
          dockerfile: "./Dockerfile"
          push: true
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
