on:
  push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Trigger external workflow and watch
        run: echo "stage 1 success"
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy step
        run: 
          | 
          echo "Deployment steps go here"
          echo "$GH_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.TEST_SECRET }}