on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Linter for Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  push_to_docker_hub:
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jothimanideriv
          password: ${{ secrets.DOCKER_LOGIN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          context: .
          tags: jothimanideriv/ghaction-poc:testing-12
  deploy_to_k3s:
    needs: push_to_docker_hub
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy step
        run: 
          | 
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -
          helm ls -nactions-runner-system
          helm ls -A