name: Dockerfile Standard Checks
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
