name: Dockerfile Standard Checks
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: shivanandderiv/ghactions
  DOCKERFILE_PATH: "./Dockerfile"
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: shivanand-deriv/ci-actions-docker-build/build_and_test@shiva/multiple_tags_input
        with:
          images: ${{ env.IMAGE_NAME }}
          project_type: skip
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          push: false
          tags: |
            v2
            latest2
  push_to_prod_registry:
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: production-registry    
    steps:
      - uses: deriv-iac/shared-actions/push_to_registry@multiple_tags_input
        with:
          images: ${{ env.IMAGE_NAME }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          push: true
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
  # k3s_deployment:
  #   needs: push_to_prod_registry
  #   runs-on: ubuntu-latest
  #   environment: production-deploy-k3s
  #   steps:
      # - uses: deriv-iac/shared-actions/deploy_to_k3s@master
      #   with:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
