on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Linter for Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  push_to_docker_hub:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: docker/login-action@v3
      - name: Login to Docker Hub
        with:
          username: jothimanideriv
          password: ${{ secrets.DOCKER_LOGIN }}
      - name: Build And pushing
      id: build
      uses: docker/build-push-action@v5
      with:
        push: true
        file: action_caller/Dockerfile
        context: action_caller
        tags: test
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy step
        run: 
          | 
          echo "Deployment steps go here"
          echo "$GH_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.TEST_SECRET }}