on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Linter for Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  deploy_to_k3s:
    needs: build_and_test
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy step
        run: 
          | 
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -
          helm ls -nactions-runner-system
          helm ls -A